package aplicacion.gestion.agenda.gestion.interfaces;

public interface _Interface {
	public String _txt_agenda="_txt_agenda";
	public String _txt_idaviso="_txt_idaviso";
	public String _txt_idvendedor="_txt_idvendedor";
	public String _txt_idcreador="_txt_idcreador";
	public String _txt_titulo="_txt_titulo";
	public String _txt_mensaje="_txt_mensaje";
	public String _btn_mostrar="_btn_mostrar";
	public String _btn_fecha="_btn_fecha";
	public String _btn_cancelar="_btn_cancelar";
	public String _btn_salir="_btn_salir";
	public String _btn_nuevo_aviso="_btn_nuevo_aviso";
	public String _btn_editar_aviso="_btn_editar_aviso";
	public String _btn_recategorizar_aviso="_btn_recategorizar_aviso";
	public String _btn_error="_btn_error";
	public String _btn_nuevo="_btn_nuevo";
	public String _btn_guardar="_btn_guardar";
	public String _btn_eliminar="_btn_eliminar";
	public String _event_updated="Updated";
	public String _event_showew="Showed";
	public String _event_deleted="Deleted";
	public String _event_readed="Readed";
	public String _tree="_tree";
	public String _lst_posponer="_lst_posponer";
	public String _table_dias="_table_dias";
	public String _table_diario="_table_diario";
	public String _table_semanal="_table_semanal";
	public String _table_mensual="_table_mensual";
	public String _table_semanal_item="_table_semanal_item";
	public String _table_day_item="_table_day_item";
	public String _lst_anio="_lst_anio";
	public String _lst_mes="_lst_mes";
	public String _btn_propiedades_guardar="_btn_propiedades_guardar";
	public String _btn_propiedades_color="_btn_propiedades_color";
	public String _btn_nueva_categoria="_btn_nueva_categoria";
	public String _btn_eliminar_categoria="_btn_eliminar_categoria";
	public String _btn_renombrar_categoria="_btn_renombrar_categoria";
	public String _chk_aviso_semanal="_chk_aviso_semanal";
	public String _chk_aviso_day="_chk_aviso_day";
	public String _chk_tree="_chk_tree";
	public String _chk_aviso_mensual="_chk_aviso_mensual";
	public String _table_mensual_item="_table_mensual_item";
	public String _btn_hoy="_btn_hoy";
	public String _btn_cargar="_btn_cargar";
}
